FIX:   a shoot in the dark, the /tap/ might be the cause of this error.  The homebrew should goto "iceman1001/homebrew-proxmark3/...
"Authentication failed for 'https://github.com/iceman1001/homebrew-tap/'
Error: Failure while executing: git clone https://github.com/iceman1001/homebrew-tap /usr/local/Homebrew/Library/Taps/iceman1001/homebrew-tap --depth=1
"